server:
  port: 8080
  request:
      maxRequestSize: 2048mb
project:
  sqlPrint: false
  beanPackage: com.cym.model
  home: /home/nginxWebUI/
  findPass: false
  
solon:
  app:
    name: nginxWebUI
  mime:
    pdf: "application/octet-stream"
  view:
    mapping:
      html: FreemarkerRender
  logging:
    logger:
      "org.eclipse.jetty":
        level: "WARN"
      "com.zaxxer":
        level: "WARN"
    appender:
      file:
        name: ${project.home}/log/${solon.app.name}
        level: INFO

spring:
  database:
    type: h2
  datasource:
    url: 
    username: 
    password: 
