server:
  port: 8080
 
project:
  version: 3.0.0
  sqlPrint: false
  beanPackage: com.cym.model
  home: /home/nginxWebUI/
  
solon:
  app.name: nginxWebUI
  view.mapping.html: FreemarkerRender

spring:
  database:
    type: mysql
  datasource:
    url: 
    username: 
    password: 
