server:
  port: 18080
  request:
    maxBodySize: 20mb
    maxFileSize: 2048mb
    maxHeaderSize: 200kb

project:
  sqlPrint: false
  beanPackage: com.cym.model
  home: /tmp/nginxWebUI/
  findPass: false
  
solon:
  app:
    name: nginxWebUI
  view:
    mapping:
      html: FreemarkerRender
  logging:
    logger:
      "io.undertow":
        level: "WARN"
      "org.xnio":
        level: "WARN"
      "o.xnio":
        level: "WARN"
      "com.zaxxer.hikari":
        level: "WARN"
      "org.jboss":
        level: "WARN"
    appender:
      console:
        level: INFO
      file:
        name: ${project.home}/log/${solon.app.name}
        level: INFO
        maxFileSize: "100 MB"
        maxHistory: "7"
spring:
  database:
    type: org.postgresql.Driver
    tablePrefix: "\""
    tableSuffix: "\""
    columnPrefix: "\""
    columnSuffix: "\""
    idColumn: id
    orderTypeInt: BIGINT
    #limitScript: "(function() { return \" LIMIT \" + offset + \",\" + limit;})();"
    limitScript: "(function() { return \" LIMIT \" + limit + \" offset \" + offset; })();"
  datasource:
    url: jdbc:postgresql://postgresql:5432/nginxwebui?charset\=utf-8
    username: postgres
    password: 123456

initAdmin: admin
initPass: Admin888
initApi: Admin888
#spring:
#  database:
#    type: sqlite
#  datasource:
#    url:
#    username:
#    password:
#
#initAdmin:
#initPass:
#initApi: